<h3>Offices</h3><br/>
<?php
/**
 * @var $this Drazen_Address_Block_Configurable
 */
$cities = $this->getDistinctCities();
$visibility = isset($_POST['city']) ? 'visible' : 'hidden'; //set button visibility attribut

?>
<div>
	<?php if (count($cities) > 0): ?>
		<form action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post">
			<select name="city" id="cities" onchange="this.form.submit()">
				<option value="">-- Please Select --</option>
				<?php foreach ($cities as $key => $city): ?>
					<option value="<?php echo $city; ?>">
						<?php echo $city; ?>
					</option>
				<?php endforeach; ?>
			</select>
		</form>
	<?php endif; ?>
	<button
		onclick="document.location.reload();"
		style="margin-left:20px;visibility:<?php echo $visibility; ?>;">
		Show all offices
	</button>
</div>
<br/>
<hr>
<br/>
<?php
if (isset($_POST['city'])) {
	$allData = $this->filterByCity($_POST['city']);
	$this->renderListOffices($allData);
} else {
	$allData = $this->getAllAddresses();
	$this->renderListOffices($allData);
}
?>

